import{createHmac}from'node:crypto';import{createClient}from'@supabase/supabase-js';import{describe,expect,it}from'vitest';import{provisionLocalCanonicalOwner,createLocalReceipt}from'../helpers/local-canonical'
const url=process.env.LOCAL_SUPABASE_URL,anon=process.env.LOCAL_SUPABASE_ANON_KEY,key=process.env.LOCAL_SUPABASE_SERVICE_ROLE_KEY,enabled=process.env.RUN_LOCAL_SUPABASE_INTEGRATION==='1'&&Boolean(url&&anon&&key),suite=enabled?describe:describe.skip
const h=(kind:string,id:string,secret:string)=>createHmac('sha256',secret).update(`writeoffs-deletion:v1:${kind}:${id}`).digest('hex')
suite('account deletion and restore reconciliation against local PostgreSQL',()=>{
 it('deletes one tenant idempotently, preserves another, and reapplies an external tombstone after restore',async()=>{const admin=createClient(url!,key!,{auth:{persistSession:false}}),secret='local-test-deletion-hmac-secret-at-least-32-bytes',a=await provisionLocalCanonicalOwner({admin,url:url!,anonKey:anon!,label:'delete-a',amounts:[-12500]}),b=await provisionLocalCanonicalOwner({admin,url:url!,anonKey:anon!,label:'delete-b',amounts:[-9900]})
  for(const owner of[a,b])expect((await admin.rpc('create_business_membership_grant',{p_business_id:owner.businessId,p_plan:'business',p_starts_at:new Date().toISOString(),p_ends_at:null,p_request_key:`deletion-test:${crypto.randomUUID()}`,p_reason:'Deletion integration test',p_provenance:'local_setup',p_actor_user_id:null})).error).toBeNull()
  const aPath=`receipts/${a.userId}/deletion-test.pdf`,bPath=`receipts/${b.userId}/keep-test.pdf`;await createLocalReceipt({userId:a.userId,storagePath:aPath});expect((await admin.storage.from('receipts').upload(aPath,Buffer.from('private-a'))).error).toBeNull();expect((await admin.storage.from('receipts').upload(bPath,Buffer.from('private-b'))).error).toBeNull();const vehicleResult=await a.customer.from('business_vehicles').insert({business_id:a.businessId,slot:1,display_name:'Work car'}).select('id').single();expect(vehicleResult.error).toBeNull();const vehicle=vehicleResult.data!;expect((await a.customer.rpc('record_canonical_mileage',{p_id:crypto.randomUUID(),p_vehicle_id:vehicle.id,p_miles_milli:12375,p_occurred_on:'2026-09-01',p_job_label:'Client',p_destination:'Office',p_business_purpose:'Client visit',p_request_key:`mileage:${crypto.randomUUID()}`})).error).toBeNull()
  const requestId=crypto.randomUUID(),businessHash=h('business',a.businessId,secret),userHash=h('user',a.userId,secret);expect((await admin.from('account_deletion_requests').insert({id:requestId,business_id:a.businessId,owner_user_id:a.userId,business_identity_hash:businessHash,user_identity_hash:userHash,reason:'customer_request',status:'scheduled',requested_at:'1900-01-01T00:00:00Z',scheduled_for:'1900-01-01T00:00:00Z',request_key:`test:${requestId}`})).error).toBeNull()
  const bRequest=crypto.randomUUID();expect((await admin.from('account_deletion_requests').insert({id:bRequest,business_id:b.businessId,owner_user_id:b.userId,business_identity_hash:h('business',b.businessId,secret),user_identity_hash:h('user',b.userId,secret),reason:'customer_request',status:'scheduled',requested_at:new Date().toISOString(),scheduled_for:'2099-01-01T00:00:00Z',request_key:`test:${bRequest}`})).error).toBeNull();expect((await a.customer.from('account_deletion_requests').select('id')).data).toEqual([{id:requestId}]);expect((await b.customer.from('account_deletion_requests').select('id')).data).toEqual([{id:bRequest}]);expect((await a.customer.from('account_deletion_tombstones').select('id')).error).not.toBeNull()
  const lease=crypto.randomUUID(),claimed=await admin.rpc('claim_due_account_deletions',{p_limit:20,p_lease_token:lease,p_now:new Date().toISOString()});expect(claimed.data?.some((row:{id:string})=>row.id===requestId)).toBe(true);expect((await admin.storage.from('receipts').remove([aPath])).error).toBeNull();expect((await admin.rpc('delete_customer_application_data',{p_request_id:requestId,p_lease_token:lease,p_now:new Date().toISOString()})).error).toBeNull();expect((await admin.auth.admin.deleteUser(a.userId)).error).toBeNull();expect((await admin.rpc('complete_account_deletion',{p_request_id:requestId,p_lease_token:lease,p_now:new Date().toISOString()})).data).toBe(true)
  expect((await admin.from('businesses').select('id').eq('id',a.businessId)).data).toEqual([]);expect((await admin.from('financial_transactions').select('id').eq('business_id',b.businessId)).data).toHaveLength(1);expect((await admin.storage.from('receipts').list(`receipts/${a.userId}`)).data).toEqual([]);expect((await admin.storage.from('receipts').download(bPath)).data).not.toBeNull();const tombstone=await admin.from('account_deletion_tombstones').select('*').eq('deletion_request_id',requestId).single();expect(tombstone.data).toMatchObject({business_identity_hash:businessHash,user_identity_hash:userHash});expect(JSON.stringify(tombstone.data)).not.toContain('12500')
  const restored=await provisionLocalCanonicalOwner({admin,url:url!,anonKey:anon!,label:'restored-delete',amounts:[-5000]}),restoredPath=`receipts/${restored.userId}/restored-private.pdf`;await createLocalReceipt({userId:restored.userId,storagePath:restoredPath});expect((await admin.storage.from('receipts').upload(restoredPath,Buffer.from('restored-private'))).error).toBeNull();const restoredEntry={deletion_request_id:crypto.randomUUID(),business_identity_hash:h('business',restored.businessId,secret),user_identity_hash:h('user',restored.userId,secret),reason:'customer_request',effective_at:new Date().toISOString()};const reconciled=await admin.rpc('reconcile_restored_deletion_tombstones',{p_entries:[restoredEntry],p_hmac_key:secret,p_now:new Date().toISOString()});expect(reconciled.error).toBeNull();expect(reconciled.data).toBe(1);const replay=await admin.rpc('reconcile_restored_deletion_tombstones',{p_entries:[restoredEntry],p_hmac_key:secret,p_now:new Date().toISOString()});expect(replay.error).toBeNull();expect(replay.data).toBe(1);const restoredRequest=await admin.from('account_deletion_requests').select('id').eq('business_id',restored.businessId).single();expect(restoredRequest.error).toBeNull();const restoreLease=crypto.randomUUID();expect((await admin.rpc('claim_due_account_deletions',{p_limit:20,p_lease_token:restoreLease,p_now:new Date().toISOString()})).data?.some((row:{id:string})=>row.id===restoredRequest.data!.id)).toBe(true);expect((await admin.storage.from('receipts').remove([restoredPath])).error).toBeNull();expect((await admin.rpc('delete_customer_application_data',{p_request_id:restoredRequest.data!.id,p_lease_token:restoreLease,p_now:new Date().toISOString()})).error).toBeNull();expect((await admin.auth.admin.deleteUser(restored.userId)).error).toBeNull();expect((await admin.rpc('complete_account_deletion',{p_request_id:restoredRequest.data!.id,p_lease_token:restoreLease,p_now:new Date().toISOString()})).data).toBe(true);expect((await admin.from('businesses').select('id').eq('id',restored.businessId)).data).toEqual([]);expect((await admin.storage.from('receipts').list(`receipts/${restored.userId}`)).data).toEqual([]);expect((await admin.rpc('reconcile_restored_deletion_tombstones',{p_entries:[restoredEntry],p_hmac_key:secret,p_now:new Date().toISOString()})).data).toBe(0)
  await admin.auth.admin.deleteUser(b.userId)
 },20000)
})
