import 'server-only'

import{createHash,randomUUID}from'node:crypto';import type{SupabaseClient}from'@supabase/supabase-js';import{createServerAdminSupabase}from'../../../utils/supabase/admin';import{decryptNotificationRecipient,encryptNotificationRecipient}from'../account-lifecycle/notification-crypto';import{NotificationDeliveryError,sendLifecycleEmail}from'../account-lifecycle/notification-provider'
type Alert={id:string;alert_type:string;safe_code:string|null;subject_hash:string|null;first_seen_at:string;last_seen_at:string;occurrence_count:number}
type Delivery={id:string;semantic_key:string;recipient_ciphertext:string;attempt_count:number;alert_id:string}
const hash=(value:string)=>createHash('sha256').update(value).digest('hex'),escape=(value:string)=>value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]!))
function environment(){const value=process.env.WRITEOFFS_ENVIRONMENT??process.env.APP_ENV;if(value!=='staging'&&value!=='production')throw new Error('OPERATIONAL_ALERT_ENVIRONMENT_INVALID');return value}
export function operationalAlertTemplate(alert:Alert){const env=environment().toUpperCase(),component=alert.alert_type.includes('notification')?'Lifecycle notifications':alert.alert_type.includes('tombstone')?'Deletion restore protection':'Account lifecycle',code=alert.safe_code??'OPERATIONAL_FAILURE',subject=`[WriteOffs ${env}] Critical ${component.toLowerCase()} alert`,lines=[`Severity: CRITICAL`,`Component: ${component}`,`Safe code: ${code}`,`First seen: ${alert.first_seen_at}`,`Most recent: ${alert.last_seen_at}`,`Occurrences: ${alert.occurrence_count}`,alert.subject_hash?`Reference: ${alert.subject_hash.slice(0,12)}`:null,`Action: Inspect the ${env} operational alert and its safe diagnostics.`].filter(Boolean)as string[],text=lines.join('\n'),html=`<!doctype html><html><body><main style="font-family:system-ui,sans-serif;max-width:600px;margin:auto;padding:24px"><h1 style="font-size:22px">Critical WriteOffs ${escape(component.toLowerCase())} alert</h1>${lines.map(line=>`<p>${escape(line)}</p>`).join('')}</main></body></html>`;return{subject,text,html}}
export async function materializeOperationalAlertDeliveries(admin:SupabaseClient,now=new Date()){const recipient=process.env.OPERATIONAL_ALERT_EMAIL_TO?.trim().toLowerCase();if(!recipient)throw new Error('OPERATIONAL_ALERT_RECIPIENT_UNCONFIGURED');const alerts=await admin.from('lifecycle_operational_alerts').select('id,alert_type,safe_code,subject_hash,first_seen_at,last_seen_at,occurrence_count').eq('severity','critical').eq('status','open');if(alerts.error)throw new Error('OPERATIONAL_ALERT_SCAN_FAILED');const window=now.toISOString().slice(0,13);for(const alert of(alerts.data??[])as Alert[]){const row={alert_id:alert.id,semantic_key:`operational-alert:${alert.id}:${window}`,incident_window:`${window}:00:00.000Z`,recipient_ciphertext:encryptNotificationRecipient(recipient),recipient_hash:hash(recipient),scheduled_for:now.toISOString(),recipient_expires_at:new Date(now.getTime()+30*86400000).toISOString()};const result=await admin.from('operational_alert_delivery_outbox').upsert(row,{onConflict:'semantic_key',ignoreDuplicates:true});if(result.error)throw new Error('OPERATIONAL_ALERT_QUEUE_FAILED')}}
export async function drainOperationalAlertDeliveries(limit=10){const admin=createServerAdminSupabase(),now=new Date();await materializeOperationalAlertDeliveries(admin,now);const lease=randomUUID(),claimed=await admin.rpc('claim_due_operational_alert_deliveries',{p_limit:limit,p_lease_token:lease,p_now:now.toISOString()});if(claimed.error)throw new Error('OPERATIONAL_ALERT_CLAIM_FAILED');const results=[]as Array<{id:string;status:string;code?:string}>;for(const row of(claimed.data??[])as Delivery[]){const found=await admin.from('lifecycle_operational_alerts').select('id,alert_type,safe_code,subject_hash,first_seen_at,last_seen_at,occurrence_count').eq('id',row.alert_id).single();try{if(found.error||!found.data)throw new Error('OPERATIONAL_ALERT_NOT_FOUND');const message=operationalAlertTemplate(found.data as Alert),sent=await sendLifecycleEmail({...message,to:decryptNotificationRecipient(row.recipient_ciphertext),idempotencyKey:row.semantic_key,attemptNumber:row.attempt_count,from:process.env.OPERATIONAL_ALERT_EMAIL_FROM,replyTo:process.env.OPERATIONAL_ALERT_EMAIL_REPLY_TO}),done=await admin.rpc('complete_operational_alert_delivery',{p_id:row.id,p_lease_token:lease,p_provider_id:sent.id,p_provider_fingerprint:hash(sent.id),p_now:new Date().toISOString()});if(done.error||done.data!==true)throw new Error('OPERATIONAL_ALERT_COMPLETION_FAILED');results.push({id:row.id,status:'delivered'})}catch(error){const provider=error instanceof NotificationDeliveryError?error:null,code=provider?.code??(error instanceof Error&&/^[A-Z0-9_]{1,100}$/.test(error.message)?error.message:'OPERATIONAL_ALERT_DELIVERY_FAILED');await admin.rpc('fail_operational_alert_delivery',{p_id:row.id,p_lease_token:lease,p_safe_code:code,p_permanent:provider?.permanent??false,p_now:new Date().toISOString()});results.push({id:row.id,status:provider?.permanent?'terminal_failed':'retryable',code})}}return results}
