import{randomUUID}from'node:crypto';import{createClient}from'@supabase/supabase-js';import{expect,test,type Page}from'@playwright/test'
const url=process.env.LOCAL_SUPABASE_URL,anon=process.env.LOCAL_SUPABASE_ANON_KEY,service=process.env.LOCAL_SUPABASE_SERVICE_ROLE_KEY,enabled=process.env.RUN_LOCAL_MEMBERSHIP_E2E==='1'&&Boolean(url&&anon&&service)
test.skip(!enabled,'requires explicitly enabled local Supabase membership E2E')
const admin=()=>createClient(url!,service!,{auth:{persistSession:false,autoRefreshToken:false}})
async function member(plan:'expenses'|'business'|null,expired=false){const client=admin(),email=`membership-browser-${randomUUID()}@example.test`,password=`Local-${randomUUID()}-password`,created=await client.auth.admin.createUser({email,password,email_confirm:true});expect(created.error).toBeNull();const userId=created.data.user!.id,business=(await client.from('businesses').select('id').eq('owner_user_id',userId).single()).data!;if(plan){const now=Date.now(),result=await client.rpc('create_business_membership_grant',{p_business_id:business.id,p_plan:plan,p_starts_at:new Date(now-(expired?2:0)*86400000).toISOString(),p_ends_at:expired?new Date(now-86400000).toISOString():null,p_request_key:`e2e:${randomUUID()}`,p_reason:'Browser membership test',p_provenance:'local_setup',p_actor_user_id:null});expect(result.error).toBeNull()}return{email,password,userId}}
async function login(page:Page,user:{email:string;password:string}){await page.goto('/login');await page.getByPlaceholder('you@example.com').fill(user.email);await page.getByPlaceholder('Your password').fill(user.password);await page.getByRole('button',{name:'Log in'}).click()}
test('renders Expenses, Business, no-membership, and historical membership boundaries',async({page})=>{const users=[]as Array<{email:string;password:string;userId:string}>;try{
 const expenses=await member('expenses');users.push(expenses);await login(page,expenses);await page.waitForURL('**/home');await expect(page.getByText('Business income')).toHaveCount(0);await page.goto('/invoices');await expect(page.getByRole('heading',{name:'Your invoice history stays available.'})).toBeVisible();await page.goto('/settings/billing');await expect(page.getByRole('heading',{name:'WriteOffs Expenses'})).toBeVisible()
 const business=await member('business');users.push(business);await page.context().clearCookies();await login(page,business);await page.waitForURL('**/home');await expect(page.getByText('Business income')).toBeVisible();await page.goto('/invoices');await expect(page.getByRole('heading',{name:'Your invoices',exact:true})).toBeVisible()
 const expired=await member('business',true);users.push(expired);await page.context().clearCookies();await login(page,expired);await page.waitForURL('**/membership/read-only');await expect(page.getByRole('heading',{name:'Your records are still here.'})).toBeVisible();await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 const none=await member(null);users.push(none);await page.context().clearCookies();await login(page,none);await page.waitForURL('**/membership');await expect(page.getByRole('heading',{name:'Choose how WriteOffs should help'})).toBeVisible()
 }finally{const client=admin();for(const user of users)await client.auth.admin.deleteUser(user.userId)}})
