'use client'
import type {GuidedWorkProjection} from '../lib/bookkeeping/guided-work-projection'
import Link from 'next/link'
import {useRef,useState} from 'react'
import {useRouter} from 'next/navigation'
import type {SpecialWork} from '../lib/bookkeeping/special-transactions'
import {DocumentIntake} from '../documents/DocumentIntake'
import {MerchantIdentity} from './guided/MerchantIdentity'
import {returnLabel,safeReturnTo} from '../lib/navigation-context'
export function SpecialTransactionFlow({work,returnTo:origin,embedded=false,onResolved,onRecoveryRefresh,onOrdinaryRequest,onPending,onEvidenceReceived}:{onEvidenceReceived?:()=>Promise<void>;onPending?:(pending:boolean)=>void;work:SpecialWork;returnTo:string;embedded?:boolean;onResolved?:(deferred:boolean,message?:string,work?:GuidedWorkProjection)=>Promise<void>;onRecoveryRefresh?:()=>Promise<void>;onOrdinaryRequest?:()=>void}){
 const router=useRouter(),lock=useRef(false),request=useRef<{signature:string;id:string}|null>(null)
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[business,setBusiness]=useState(''),[selected,setSelected]=useState(work.kind==='refund'&&work.candidates.length===1?work.candidates[0].recordId:''),[deferred,setDeferred]=useState(false),[none,setNone]=useState(false),[finished,setFinished]=useState(false)
 const needsSupportingRecord=work.lastAction==='unsure'&&work.kind!=='loan'
 const PurchaseHeading=embedded?'h1':'h2'
 const returnTo=safeReturnTo(origin,'/home')
 async function answer(action:string,original?:string,businessCents?:number){
  if(lock.current)return;lock.current=true;onPending?.(true);setBusy(true);setError('')
  const signature=JSON.stringify({expected:work.decisionId,action,original,businessCents})
  if(request.current?.signature!==signature)request.current={signature,id:crypto.randomUUID()}
  try{const r=await fetch(`/api/bookkeeping/records/${work.recordId}/special`,{method:'POST',headers:{'content-type':'application/json',...(onResolved?{'x-betti-guided':'1'}:{})},body:JSON.stringify({expected:work.decisionId,requestId:request.current.id,action,original,businessCents})});const data=await r.json();if(!r.ok)throw new Error(data.error??'Please try again.')
   if(onResolved){await onResolved(action==='defer',action==='unsure'?'A document may help me understand this.':action==='card_payment'?'Got it. This is a credit card payment, outside business income and expenses.':action==='owner_use'?'Got it. This is money taken or used personally, outside business expenses.':action==='refund_link'?'Got it. I matched the refund to that purchase.':undefined,data.work);return}
   if(action==='defer'||action==='unsure'){setDeferred(true);setMessage(action==='defer'?'I kept this on your list. Come back when you have the information.':'That’s okay. Send me a document when you have one, and I’ll take another look.')}
   else{setMessage(action==='card_payment'?'Got it. This is a credit card payment, outside business income and expenses.':action==='owner_use'?'Got it. This is money taken or used personally, outside business expenses.':action==='refund_link'?'Got it. I matched the refund to that purchase.':'Got it.');if(['card_payment','owner_use','refund_link'].includes(action))setFinished(true);else router.refresh()}
  }catch(e){setError(e instanceof Error?e.message:'Please try again.');if(onRecoveryRefresh)await onRecoveryRefresh()}finally{lock.current=false;onPending?.(false);setBusy(false)}
 }
 return <section className={embedded?"betti-special space-y-4":"mx-auto max-w-2xl space-y-4 py-5"} aria-label="Betti transaction question">
  {!embedded&&<><Link href={returnTo} className="inline-flex min-h-11 items-center font-semibold">← {returnLabel(returnTo)}</Link><p className="font-semibold">Betti</p></>}
  <p className="betti-answer-status" role="status">{busy?'Saving your answer…':'\u00a0'}</p>
  {message&&<p role="status">{message}</p>}
  {!deferred&&!finished&&<>
  {needsSupportingRecord&&<><h1>Send me a supporting record.</h1><p>Send me the payment, purchase or reimbursement record you have.</p><DocumentIntake onUploadState={(pending,result)=>{if(pending)onPending?.(true);else if(result?.received&&onEvidenceReceived)void onEvidenceReceived().catch(()=>setError('I couldn’t check the latest document status. Please refresh.')).finally(()=>onPending?.(false));else onPending?.(false)}} guided={embedded} compact recordId={work.recordId}/></>}
  {work.kind==='movement'&&!needsSupportingRecord&&<><h1 className="text-2xl font-semibold">What kind of payment was this?</h1><div className="grid gap-3">{[['card_payment','Credit card payment'],...(work.amountCents<0?[['loan_payment','Payment on a business loan'],['owner_use','Money I took or used personally']]:[])].map(([action,label])=><button className="btn btn-secondary" disabled={busy} key={action} onClick={()=>void answer(action)}>{label}</button>)}{onOrdinaryRequest?<button className="btn btn-secondary" disabled={busy} onClick={onOrdinaryRequest}>Something else</button>:<Link className="btn btn-secondary" href={`/check-in?record=${work.recordId}&ordinary=1&returnTo=${encodeURIComponent(returnTo)}`}>Something else</Link>}</div></>}
  {work.kind==='refund'&&!work.linked&&!needsSupportingRecord&&<>{(!embedded||(!work.candidates.length&&!['merchant_return','reimbursement'].includes(work.lastAction??'')))&&<><h1 className="text-2xl font-semibold">Was this money returned by a store, or did someone reimburse you?</h1><div className="flex flex-wrap gap-3"><button className="btn btn-secondary" disabled={busy} onClick={()=>void answer('merchant_return')}>Returned by the store</button><button className="btn btn-secondary" disabled={busy} onClick={()=>void answer('reimbursement')}>Someone reimbursed me</button></div></>}
   {work.lastAction==='reimbursement'?<><h1>Send me the reimbursement records.</h1><p>Send me the expense and reimbursement records so I can see what was repaid.</p><DocumentIntake onUploadState={(pending,result)=>{if(pending)onPending?.(true);else if(result?.received&&onEvidenceReceived)void onEvidenceReceived().catch(()=>setError('I couldn’t check the latest document status. Please refresh.')).finally(()=>onPending?.(false));else onPending?.(false)}} guided={embedded} compact recordId={work.recordId}/></>:(!embedded||work.lastAction==='merchant_return'||work.candidates.length>0)&&<><PurchaseHeading className="text-lg font-semibold">{work.candidates.length===1?'Is it for this purchase?':'Which purchase was it for?'}</PurchaseHeading><p>This looks like a refund. Help me match it to the purchase.</p>{work.candidates.map(c=><label className="flex min-h-12 gap-3 rounded border p-3" key={c.recordId}><input type="radio" name="return-purchase" checked={selected===c.recordId} onChange={()=>{setSelected(c.recordId);setNone(false)}}/><span><MerchantIdentity compact merchant={c.merchant} date={c.date} amountCents={c.amountCents}/>{c.crossYear&&<span className="block">From a different year. I’ll need to check the tax details.</span>}</span></label>)}
   {work.candidates.find(c=>c.recordId===selected)?.treatment==='mixed_use'&&<label className="block">How much of this refund was for business?<input className="field" inputMode="decimal" value={business} onChange={e=>setBusiness(e.target.value)}/></label>}
   <button disabled={busy||!selected} className="btn btn-primary" onClick={()=>{const mixed=work.candidates.find(c=>c.recordId===selected)?.treatment==='mixed_use';if(mixed&&!/^\d+(\.\d{1,2})?$/.test(business)){setError('Enter the business dollars from this return.');return}void answer('refund_link',selected,mixed?Math.round(Number(business)*100):undefined)}}>Yes, that’s it</button>
   <button className="btn btn-secondary" onClick={()=>setNone(true)}>I don’t see it / something else</button>{none&&<><p>Send me the original purchase or refund record so I can match them.</p><DocumentIntake onUploadState={(pending,result)=>{if(pending)onPending?.(true);else if(result?.received&&onEvidenceReceived)void onEvidenceReceived().catch(()=>setError('I couldn’t check the latest document status. Please refresh.')).finally(()=>onPending?.(false));else onPending?.(false)}} guided={embedded} compact recordId={work.recordId}/></>}</>}
  </>}
  {work.linked&&<><h1 className="text-2xl font-semibold">Refund linked</h1><p>I matched this refund to the original purchase. It won’t count as new income.</p><button className="btn btn-secondary" disabled={busy} onClick={()=>void answer('refund_unlink')}>Change the original purchase</button></>}
  {work.kind==='loan'&&<><h1 className="text-2xl font-semibold">Send me the loan statement.</h1><p>I can see this was a loan payment, but I need the statement to separate principal and interest.</p><DocumentIntake onUploadState={(pending,result)=>{if(pending)onPending?.(true);else if(result?.received&&onEvidenceReceived)void onEvidenceReceived().catch(()=>setError('I couldn’t check the latest document status. Please refresh.')).finally(()=>onPending?.(false));else onPending?.(false)}} guided={embedded} buttonLabel="Send statement" recordId={work.recordId}/></>}
  {!work.linked&&!needsSupportingRecord&&work.kind!=='loan'&&work.lastAction!=='reimbursement'&&<button className="btn btn-secondary" disabled={busy} onClick={()=>void answer('unsure')}>I’m not sure</button>}
  {!work.linked&&<button className="min-h-11 underline" disabled={busy} onClick={()=>void answer('defer')}>I’ll come back to this</button>}
  </>}
  {error&&<p role="alert" className="text-red-700">{error}</p>}
  {!embedded&&<Link href={returnTo} className="btn btn-secondary">{returnLabel(returnTo)}</Link>}
 </section>
}
