import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest'
const sql=readFileSync('supabase/migrations/20260910000100_add_customer_retention_deletion_lifecycle.sql','utf8').toLowerCase()
describe('account retention and deletion schema',()=>{
 it('models twelve-month read-only retention and seven-day customer grace',()=>{expect(sql).toContain("interval '12 months'");expect(sql).toContain("interval '7 days'");expect(sql).toContain('read_only_through');expect(sql).toContain('deletion_due_at')})
 it('requires tenant ownership and aal2 for customer destructive actions',()=>{expect(sql).toContain("auth.jwt()->>'aal'");expect(sql).toContain("<>'aal2'");expect(sql).toContain('owner_user_id=p_user_id');expect(sql).toContain('account_deletion_request_select_own')})
 it('uses a leased retryable deletion state machine',()=>{expect(sql).toContain('for update skip locked');expect(sql).toContain("status='retryable'");expect(sql).toContain('lease_token=p_lease_token');expect(sql).toContain('account_deletion_attempt_events')})
 it('keeps only minimized tombstones outside the customer foreign-key graph',()=>{const table=sql.slice(sql.indexOf('create table public.account_deletion_tombstones'),sql.indexOf('create unique index account_deletion_business_tombstone'));expect(table).not.toContain('references public.businesses');expect(table).not.toContain('description');expect(table).not.toContain('amount');expect(table).toContain('business_identity_hash');expect(table).toContain('effective_at')})
 it('reconciles tombstones before restored customers can return',()=>{expect(sql).toContain('reconcile_restored_deletion_tombstones');expect(sql).toContain("writeoffs-deletion:v1:business:");expect(sql).toContain("request_key)");expect(sql).toContain("'restore:'")})
 it('removes legacy and canonical customer data without weakening ordinary immutability',()=>{expect(sql).toContain("set_config('writeoffs.deletion_execution','on',true)");expect(sql).toContain("raise exception 'membership history is append-only'");expect(sql).toContain("delete from public.receipts where user_id=selected.owner_user_id");expect(sql).toContain("delete from public.businesses where id=selected.business_id")})
})
