export type LifecycleNoticeType='read_only_started'|'retention_30_days'|'retention_7_days'|'explicit_deletion_scheduled'|'explicit_deletion_canceled'|'deletion_completed'
type TemplateInput={type:LifecycleNoticeType;effectiveAt:string|null;timeZone:string;actionUrl:string|null;contextCode?:'active'|'read_only'|null}
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!))
function date(value:string|null,timeZone:string){if(!value)return null;const options={year:'numeric',month:'long',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}as const;try{return new Intl.DateTimeFormat('en-US',{...options,timeZone}).format(new Date(value))}catch{return new Intl.DateTimeFormat('en-US',{...options,timeZone:'UTC'}).format(new Date(value))}}
export function lifecycleNoticeTemplate(input:TemplateInput){const when=date(input.effectiveAt,input.timeZone),link=input.actionUrl?`\n\nOpen WriteOffs: ${input.actionUrl}`:'';let subject='',heading='',paragraphs:string[]=[]
 switch(input.type){
  case'read_only_started':subject='Your WriteOffs records are now read-only';heading='Your membership has ended.';paragraphs=[`Your records remain available to view and download for 12 months${when?`, until ${when}`:''}.`,`Betti is no longer adding bookkeeping, and bank syncing has stopped. You can keep reviewing and exporting your existing records.`];break
  case'retention_30_days':subject='Your WriteOffs records will be deleted in about 30 days';heading='A reminder about your records.';paragraphs=[`Your WriteOffs records are scheduled for permanent deletion${when?` on ${when}`:''}.`,`Download anything you want to keep before then. Your records remain available to view until deletion.`];break
  case'retention_7_days':subject='Your WriteOffs records will be deleted in 7 days';heading='A final reminder about your records.';paragraphs=[`Your records are scheduled for permanent deletion${when?` on ${when}`:''}.`,`Download anything you want to keep before then. After deletion, WriteOffs cannot restore your account from the live system. Encrypted disaster-recovery backups may retain deleted data temporarily until their normal expiry.`];break
  case'explicit_deletion_scheduled':subject='Your WriteOffs deletion request is scheduled';heading='We received your deletion request.';paragraphs=[`Your account and eligible records are scheduled for permanent deletion${when?` on ${when}`:''}.`,`New bookkeeping and bank syncing have stopped. You can cancel this request during the seven-day grace period or download records you want to keep.`];break
  case'explicit_deletion_canceled':subject='Your WriteOffs deletion request was canceled';heading='Your deletion request was canceled.';paragraphs=[`No permanent deletion occurred. ${input.contextCode==='read_only'?'Your records remain available in read-only form.':'Your paid service remains available through its existing paid-through date.'}`,`Billing was not restarted. If bank access was disconnected, it will not reconnect automatically.`];break
  case'deletion_completed':subject='Your WriteOffs account deletion is complete';heading='Your deletion is complete.';paragraphs=[`Eligible customer and bookkeeping data has been removed from the live WriteOffs system. Permanent restoration through WriteOffs is not available.`,`Limited billing, legal, or security records may remain where required. Encrypted disaster-recovery backups may temporarily retain deleted data until their normal expiry.`];break
 }
 const text=[heading,...paragraphs].join('\n\n')+link;const action=input.actionUrl?`<p><a href="${escapeHtml(input.actionUrl)}" style="display:inline-block;padding:11px 16px;border-radius:9px;background:#243186;color:#fff;text-decoration:none">Open WriteOffs</a></p>`:''
 const html=`<!doctype html><html><body style="margin:0;background:#f6f5ef;color:#17213d;font-family:system-ui,-apple-system,Segoe UI,sans-serif"><main style="max-width:560px;margin:auto;padding:32px 20px"><p style="font-weight:700;color:#243186">WriteOffs</p><h1 style="font-size:24px;line-height:1.25">${escapeHtml(heading)}</h1>${paragraphs.map(value=>`<p style="font-size:16px;line-height:1.55">${escapeHtml(value)}</p>`).join('')}${action}<p style="font-size:13px;color:#5c6478">This is a service message about your WriteOffs account.</p></main></body></html>`
 return{subject,text,html}
}
