import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';import{can,entitlementsFromMembership}from'../../app/lib/membership/entitlements';import{isCustomerBookkeepingMutationRoute}from'../../app/lib/route-policy'
const row=(extra:Record<string,unknown>={})=>({business_id:'b',plan:'business',lifecycle:'active',authority:'stripe',access_through:'2026-10-01T00:00:00Z',...extra})
describe('customer lifecycle product boundary',()=>{
 it('freezes all bookkeeping while preserving exports during deletion grace',()=>{const value=entitlementsFromMembership(row({deletion_status:'scheduled',deletion_request_id:'d',deletion_scheduled_for:'2026-09-17T00:00:00Z'}),new Date('2026-09-10'));expect(value.lifecycle).toBe('pending_deletion');expect(can(value,'autonomous_processing')).toBe(false);expect(can(value,'upload_receipts')).toBe(false);expect(can(value,'export_historical_records')).toBe(true)})
 it('keeps paid service until paid-through and then becomes historical',()=>{expect(entitlementsFromMembership(row(),new Date('2026-09-30')).lifecycle).toBe('active');const ended=entitlementsFromMembership(row(),new Date('2026-10-02'));expect(ended.lifecycle).toBe('expired_read_only');expect(can(ended,'export_historical_records')).toBe(true);expect(can(ended,'track_mileage')).toBe(false)})
 it('centrally identifies customer bookkeeping mutations but leaves reads and disconnect available',()=>{expect(isCustomerBookkeepingMutationRoute('/api/receipts','POST')).toBe(true);expect(isCustomerBookkeepingMutationRoute('/api/bookkeeping/questions/id','POST')).toBe(true);expect(isCustomerBookkeepingMutationRoute('/api/mileage/export','GET')).toBe(false);expect(isCustomerBookkeepingMutationRoute('/api/plaid/disconnect','POST')).toBe(false);expect(isCustomerBookkeepingMutationRoute('/api/account/deletion','POST')).toBe(false)})
 it('uses stripe period-end cancellation and never creates a refund',()=>{const route=readFileSync('app/api/membership/change/route.ts','utf8');expect(route).toContain('cancel_at_period_end:true');expect(route).not.toContain('refunds.create')})
 it('keeps cancellation and deletion distinct in customer copy',()=>{const billing=readFileSync('app/settings/billing/BillingActions.tsx','utf8'),deletion=readFileSync('app/settings/AccountDataActions.tsx','utf8');expect(billing).toContain('12 months');expect(billing).toContain('no partial-month refund');expect(deletion).toContain('seven days');expect(deletion).toContain('does not restart billing')})
 it('isolates stale inactive Plaid disconnects so they cannot block the deletion queue',()=>{const worker=readFileSync('app/lib/account-lifecycle/deletion.ts','utf8');expect(worker).toContain("try{await revokePlaidItems(admin,businessId)}catch(error)");expect(worker).toContain("Inactive Plaid disconnects need retry.");expect(worker.indexOf('await disconnectInactivePlaid(admin)')).toBeLessThan(worker.indexOf("claim_due_account_deletions"))})
})
