import{afterEach,describe,expect,it,vi}from'vitest'
import{can,entitlementsFromMembership,getLimit,membershipCatalogVersion}from'../../app/lib/membership/entitlements'
const row=(plan:'expenses'|'business',lifecycle='active',extra:Record<string,unknown>={})=>({business_id:'business-1',plan,lifecycle,authority:'stripe',access_through:'2026-09-30T00:00:00Z',...extra})
describe('canonical membership entitlements',()=>{afterEach(()=>vi.unstubAllEnvs())
 it('keeps Expenses expense-focused while contractor and ingestion remain available',()=>{const value=entitlementsFromMembership(row('expenses'),new Date('2026-08-25'));expect(can(value,'track_expenses')).toBe(true);expect(can(value,'contractor_awareness')).toBe(true);expect(can(value,'upload_receipts')).toBe(true);expect(can(value,'upload_statements')).toBe(true);expect(can(value,'import_csv')).toBe(true);expect(can(value,'record_manual_income')).toBe(false);expect(can(value,'create_invoices')).toBe(false)})
 it('adds bounded income and invoice responsibility for Business',()=>{const value=entitlementsFromMembership(row('business'),new Date('2026-08-25'));expect(can(value,'track_income')).toBe(true);expect(can(value,'record_manual_income')).toBe(true);expect(can(value,'create_invoices')).toBe(true);expect(can(value,'business_tax_package')).toBe(true)})
 it('keeps paid capabilities during payment grace and cancellation period',()=>{for(const lifecycle of['payment_issue','canceling']){const value=entitlementsFromMembership(row('business',lifecycle,{grace_through:'2026-09-01T00:00:00Z'}),new Date('2026-08-25'));expect(can(value,'create_invoices')).toBe(true)}})
 it('expires active work while preserving historical exports',()=>{const value=entitlementsFromMembership(row('business','expired_read_only'),new Date('2026-08-25'));expect(can(value,'upload_receipts')).toBe(false);expect(can(value,'create_invoices')).toBe(false);expect(can(value,'export_historical_records')).toBe(true)})
 it('fails closed without canonical authority and never reads legacy plan names',()=>{const value=entitlementsFromMembership(null);expect(value.lifecycle).toBe('none');expect(value.capabilities.size).toBe(0);expect(membershipCatalogVersion).toBe('membership-entitlements:v1')})
 it('centralizes configurable Plaid Item limits',()=>{vi.stubEnv('MEMBERSHIP_EXPENSES_PLAID_ITEM_LIMIT','4');vi.stubEnv('MEMBERSHIP_BUSINESS_PLAID_ITEM_LIMIT','9');expect(getLimit(entitlementsFromMembership(row('expenses'),new Date('2026-08-25')),'connected_plaid_item_limit')).toBe(4);expect(getLimit(entitlementsFromMembership(row('business'),new Date('2026-08-25')),'connected_plaid_item_limit')).toBe(9)})
})
