import{afterEach,describe,expect,it,vi}from'vitest';import{NotificationDeliveryError,sendLifecycleEmail}from'../../app/lib/account-lifecycle/notification-provider'
const message={to:'allowed@example.test',subject:'Subject',text:'Text',html:'<p>Text</p>',idempotencyKey:'semantic-1'}
const saved={...process.env};afterEach(()=>{process.env={...saved};vi.unstubAllGlobals()})
describe('lifecycle notification provider',()=>{
 it('accepts only an allowlisted staging sink recipient',async()=>{process.env.WRITEOFFS_ENVIRONMENT='staging';process.env.LIFECYCLE_EMAIL_MODE='sink';process.env.LIFECYCLE_EMAIL_STAGING_RECIPIENTS=message.to;await expect(sendLifecycleEmail(message)).resolves.toEqual({id:'sink_semantic-1'});await expect(sendLifecycleEmail({...message,to:'other@example.test'})).rejects.toMatchObject({code:'STAGING_RECIPIENT_NOT_ALLOWED',permanent:true})})
 it('supports a staging-only first-attempt transient failure certification',async()=>{process.env.WRITEOFFS_ENVIRONMENT='staging';process.env.LIFECYCLE_EMAIL_MODE='sink';process.env.LIFECYCLE_EMAIL_STAGING_RECIPIENTS=message.to;await expect(sendLifecycleEmail({...message,idempotencyKey:'cert-transient:fixture',attemptNumber:1})).rejects.toMatchObject({code:'NOTIFICATION_PROVIDER_NETWORK',permanent:false});await expect(sendLifecycleEmail({...message,idempotencyKey:'cert-transient:fixture',attemptNumber:2})).resolves.toEqual({id:'sink_cert-transient:fixture'})})
 it('applies the staging allowlist to real Resend delivery',async()=>{process.env.WRITEOFFS_ENVIRONMENT='staging';process.env.LIFECYCLE_EMAIL_MODE='resend';process.env.LIFECYCLE_EMAIL_STAGING_RECIPIENTS=message.to;process.env.RESEND_API_KEY='re_fixture';process.env.LIFECYCLE_EMAIL_FROM='WriteOffs <test@example.test>';const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:'provider-id'}),{status:200,headers:{'content-type':'application/json'}}));vi.stubGlobal('fetch',fetch);await expect(sendLifecycleEmail(message)).resolves.toEqual({id:'provider-id'});await expect(sendLifecycleEmail({...message,to:'other@example.test'})).rejects.toMatchObject({code:'STAGING_RECIPIENT_NOT_ALLOWED',permanent:true});expect(fetch).toHaveBeenCalledTimes(1)})
 it('classifies provider 5xx as transient',async()=>{process.env.LIFECYCLE_EMAIL_MODE='resend';process.env.RESEND_API_KEY='re_fixture';process.env.LIFECYCLE_EMAIL_FROM='WriteOffs <test@example.test>';vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('',{status:503})));await expect(sendLifecycleEmail(message)).rejects.toEqual(expect.objectContaining<Partial<NotificationDeliveryError>>({code:'NOTIFICATION_PROVIDER_UNAVAILABLE',permanent:false}))})
 it('classifies an invalid recipient response as permanent',async()=>{process.env.LIFECYCLE_EMAIL_MODE='resend';process.env.RESEND_API_KEY='re_fixture';process.env.LIFECYCLE_EMAIL_FROM='WriteOffs <test@example.test>';vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('',{status:422})));await expect(sendLifecycleEmail(message)).rejects.toEqual(expect.objectContaining<Partial<NotificationDeliveryError>>({code:'NOTIFICATION_RECIPIENT_REJECTED',permanent:true}))})
 it('requires provider acceptance and forwards the semantic idempotency key',async()=>{process.env.LIFECYCLE_EMAIL_MODE='resend';process.env.RESEND_API_KEY='re_fixture';process.env.LIFECYCLE_EMAIL_FROM='WriteOffs <test@example.test>';const fetch=vi.fn().mockResolvedValue(new Response(JSON.stringify({id:'provider-id'}),{status:200,headers:{'content-type':'application/json'}}));vi.stubGlobal('fetch',fetch);await expect(sendLifecycleEmail(message)).resolves.toEqual({id:'provider-id'});expect(fetch).toHaveBeenCalledWith('https://api.resend.com/emails',expect.objectContaining({headers:expect.objectContaining({'idempotency-key':'semantic-1'})}))})
})
