import{createClient}from'@supabase/supabase-js';import{describe,expect,it}from'vitest';import{provisionLocalCanonicalOwner}from'../helpers/local-canonical'
const url=process.env.LOCAL_SUPABASE_URL,anon=process.env.LOCAL_SUPABASE_ANON_KEY,service=process.env.LOCAL_SUPABASE_SERVICE_ROLE_KEY
const suite=process.env.RUN_LOCAL_SUPABASE_INTEGRATION==='1'&&url&&anon&&service?describe:describe.skip
suite('membership authority local PostgreSQL',()=>{it('grants explicitly, remains idempotent, and isolates tenants',async()=>{const admin=createClient(url!,service!,{auth:{persistSession:false}}),owner=await provisionLocalCanonicalOwner({admin,url:url!,anonKey:anon!,label:'membership-a',amounts:[]}),other=await provisionLocalCanonicalOwner({admin,url:url!,anonKey:anon!,label:'membership-b',amounts:[]}),key=`grant:${crypto.randomUUID()}`,starts=new Date().toISOString()
  const first=await admin.rpc('create_business_membership_grant',{p_business_id:owner.businessId,p_plan:'business',p_starts_at:starts,p_ends_at:null,p_request_key:key,p_reason:'Membership integration test',p_provenance:'local_setup',p_actor_user_id:null}),replay=await admin.rpc('create_business_membership_grant',{p_business_id:owner.businessId,p_plan:'business',p_starts_at:starts,p_ends_at:null,p_request_key:key,p_reason:'Membership integration test',p_provenance:'local_setup',p_actor_user_id:null});expect(first.error).toBeNull();expect(replay.data).toBe(first.data)
  const own=await owner.customer.from('current_customer_membership').select('plan,lifecycle').single(),isolated=await other.customer.from('current_customer_membership').select('*');expect(own.data).toEqual({plan:'business',lifecycle:'active'});expect(isolated.data).toEqual([])
  const forged=await owner.customer.from('business_memberships').insert({business_id:owner.businessId,plan:'business',lifecycle:'active',authority:'grant'});expect(forged.error).not.toBeNull()
  const legacy=await admin.from('subscriptions').insert({user_id:other.userId,plan:'pro+',status:'active'}).select().maybeSingle();if(!legacy.error){const noMembership=await other.customer.from('current_customer_membership').select('*');expect(noMembership.data).toEqual([])}
 })
 it('rejects duplicate and stale provider events without regressing state',async()=>{const admin=createClient(url!,service!,{auth:{persistSession:false}}),owner=await provisionLocalCanonicalOwner({admin,url:url!,anonKey:anon!,label:'membership-events',amounts:[]}),newer=new Date('2026-08-25T12:00:00Z').toISOString(),older=new Date('2026-08-25T11:00:00Z').toISOString(),event=`evt_${crypto.randomUUID()}`
  const args={p_stripe_event_id:event,p_event_type:'customer.subscription.created',p_provider_created_at:newer,p_business_id:owner.businessId,p_customer_id:`cus_${crypto.randomUUID()}`,p_subscription_id:`sub_${crypto.randomUUID()}`,p_plan:'business',p_lifecycle:'active',p_access_through:'2026-09-25T00:00:00Z',p_grace_through:null,p_cancel_at_period_end:false,p_scheduled_plan:null,p_scheduled_effective_at:null,p_membership_event_type:'activated'}
  expect((await admin.rpc('apply_stripe_membership_event',args)).data).toBe('applied');expect((await admin.rpc('apply_stripe_membership_event',args)).data).toBe('duplicate');expect((await admin.rpc('apply_stripe_membership_event',{...args,p_stripe_event_id:`evt_${crypto.randomUUID()}`,p_provider_created_at:older,p_plan:'expenses'})).data).toBe('stale');const current=await admin.from('business_memberships').select('plan').eq('business_id',owner.businessId).single();expect(current.data?.plan).toBe('business')
 })})
