import{createHmac}from'node:crypto';import{describe,expect,it,vi}from'vitest';import{recordResendLifecycleEvent,verifyResendWebhook}from'../../app/lib/account-lifecycle/resend-webhooks'
const secret=`whsec_${Buffer.from('a secure webhook test secret').toString('base64')}`,id='msg_webhook_fixture',timestamp='1789070400',payload=JSON.stringify({type:'email.bounced',created_at:'2026-09-10T20:00:00.000Z',data:{email_id:'provider-id'}})
function signature(body=payload){return`v1,${createHmac('sha256',Buffer.from(secret.slice(6),'base64')).update(`${id}.${timestamp}.${body}`).digest('base64')}`}
describe('Resend lifecycle webhook',()=>{
 it('verifies the raw signed payload and accepts lifecycle delivery events',()=>{expect(verifyResendWebhook({payload,id,timestamp,signature:signature(),secret,now:Number(timestamp)*1000})).toEqual({type:'email.bounced',createdAt:'2026-09-10T20:00:00.000Z',emailId:'provider-id'})})
 it('rejects tampering, missing signatures, stale timestamps, and unrelated events',()=>{expect(()=>verifyResendWebhook({payload:`${payload} `,id,timestamp,signature:signature(),secret,now:Number(timestamp)*1000})).toThrow('INVALID_RESEND_WEBHOOK');expect(()=>verifyResendWebhook({payload,id,timestamp,signature:null,secret,now:Number(timestamp)*1000})).toThrow('INVALID_RESEND_WEBHOOK');expect(()=>verifyResendWebhook({payload,id,timestamp,signature:signature(),secret,now:Number(timestamp)*1000+301000})).toThrow('INVALID_RESEND_WEBHOOK');const other=JSON.stringify({type:'email.opened',created_at:'2026-09-10T20:00:00.000Z',data:{email_id:'provider-id'}});expect(()=>verifyResendWebhook({payload:other,id,timestamp,signature:signature(other),secret,now:Number(timestamp)*1000})).toThrow('INVALID_RESEND_WEBHOOK')})
 it('passes only hashes and provider identifiers to the idempotent database function',async()=>{const rpc=vi.fn().mockResolvedValue({data:true,error:null}),admin={rpc}as never;await expect(recordResendLifecycleEvent(admin,{eventId:id,event:{type:'email.complained',createdAt:'2026-09-10T20:00:00.000Z',emailId:'provider-id'}})).resolves.toEqual({recorded:true});expect(rpc).toHaveBeenCalledWith('record_resend_lifecycle_webhook',expect.objectContaining({p_event_key_hash:expect.stringMatching(/^[a-f0-9]{64}$/),p_provider_message_fingerprint:expect.stringMatching(/^[a-f0-9]{64}$/)}));expect(JSON.stringify(rpc.mock.calls)).not.toContain('@')})
 it('treats a repeated provider event as an acknowledged duplicate',async()=>{const admin={rpc:vi.fn().mockResolvedValue({data:false,error:null})}as never;await expect(recordResendLifecycleEvent(admin,{eventId:id,event:{type:'email.delivered',createdAt:'2026-09-10T20:00:00.000Z',emailId:'provider-id'}})).resolves.toEqual({recorded:false})})
})
