import {NextResponse}from'next/server'
import {createServerSupabase}from'../../../utils/supabase/server'
import{listContractorSummaries}from'../../lib/bookkeeping/contractor-awareness'
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const methods=new Set(['cash','check','ach_zelle','payment_card','third_party_service','other','unknown'])
export async function GET(request:Request){const supabase=await createServerSupabase(),{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'unauthorized'},{status:401});const{data:business}=await supabase.from('businesses').select('id').eq('owner_user_id',user.id).single();if(!business)return NextResponse.json({error:'business_unavailable'},{status:404});const year=Number(new URL(request.url).searchParams.get('year')??new Date().getFullYear());if(!Number.isInteger(year)||year<2000||year>2100)return NextResponse.json({error:'invalid_year'},{status:400});return NextResponse.json({contractors:await listContractorSummaries({supabase,businessId:business.id,taxYear:year})})}
export async function POST(request:Request){const supabase=await createServerSupabase(),{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'unauthorized'},{status:401});let body:Record<string,unknown>;try{body=await request.json()}catch{return NextResponse.json({error:'invalid_request'},{status:400})}const key=request.headers.get('idempotency-key')??'';if(!/^[\w:-]{1,120}$/.test(key))return NextResponse.json({error:'invalid_request'},{status:400});try{
 if(body.action==='create'){const name=typeof body.displayName==='string'?body.displayName.trim():'';const businessName=typeof body.businessName==='string'?body.businessName.trim():'';const{data,error}=await supabase.rpc('create_canonical_contractor',{p_display_name:name,p_business_name:businessName,p_request_key:key});if(error)throw error;return NextResponse.json({ok:true,contractorId:data})}
 if(body.action==='correct'&&uuid.test(String(body.contractorId))&&uuid.test(String(body.expectedEventId))){const{error}=await supabase.rpc('correct_canonical_contractor',{p_contractor_id:body.contractorId,p_expected_event_id:body.expectedEventId,p_display_name:body.displayName,p_business_name:body.businessName??'',p_active:body.active!==false,p_request_key:key});if(error)throw error;return NextResponse.json({ok:true})}
 if(body.action==='w9'&&uuid.test(String(body.contractorId))&&uuid.test(String(body.expectedEventId))&&['unknown','needed','on_file','needs_attention'].includes(String(body.status))){const{error}=await supabase.rpc('record_contractor_w9_status',{p_contractor_id:body.contractorId,p_expected_event_id:body.expectedEventId,p_status:body.status,p_evidence_note:typeof body.evidenceNote==='string'?body.evidenceNote:'',p_request_key:key});if(error)throw error;return NextResponse.json({ok:true})}
 if(body.action==='associate'&&uuid.test(String(body.recordId))&&uuid.test(String(body.contractorId))&&methods.has(String(body.paymentMethod))){let method=String(body.paymentMethod),source=method==='unknown'?'unknown':'customer';const{data:manual}=await supabase.from('current_manual_financial_activity').select('payment_method').eq('bookkeeping_record_id',body.recordId).maybeSingle();if(manual?.payment_method){const mapped:Record<string,string>={cash:'cash',check:'check',zelle_ach:'ach_zelle',card:'payment_card',personal_card:'payment_card',other:'other'};method=mapped[String(manual.payment_method)]??method;source='manual_source'}const expected=uuid.test(String(body.expectedEventId))?body.expectedEventId:null;const{error}=await supabase.rpc('associate_contractor_payment',{p_bookkeeping_record_id:body.recordId,p_contractor_id:body.contractorId,p_expected_event_id:expected,p_payment_method:method,p_payment_method_source:source,p_remove:body.remove===true,p_request_key:key});if(error)throw error;return NextResponse.json({ok:true})}
 return NextResponse.json({error:'invalid_request'},{status:400})
 }catch(cause){const message=cause instanceof Error?cause.message:'';return NextResponse.json({error:/changed/i.test(message)?'This information changed. Reload and try again.':'Unable to save contractor information safely.'},{status:/changed/i.test(message)?409:400})}}
