import{describe,expect,it}from'vitest'
import{readFileSync}from'node:fs'
const weekly=readFileSync('app/home/WeeklyReview.tsx','utf8')
const processing=readFileSync('app/lib/bookkeeping/weekly-review-processing.ts','utf8')
const questions=readFileSync('app/questions/page.tsx','utf8')
const workflowRoute=readFileSync('app/api/bookkeeping/reviews/[id]/workflow/route.ts','utf8')
const weeklyReadModel=readFileSync('app/lib/bookkeeping/weekly-review.ts','utf8')
const periodActionRoute=readFileSync('app/api/bookkeeping/reviews/[id]/route.ts','utf8')
const styles=readFileSync('app/globals.css','utf8')

describe('transaction-first weekly review',()=>{
 it('orders exception sweeps before questions and documentation',()=>{
  expect(weekly).toContain("personal:'mixed',mixed:'questions',questions:'documentation',documentation:'mileage',mileage:'final'")
  expect(weekly).toContain('First, take a quick look at this week’s transactions.')
  expect(weekly).toContain('Check anything that was personal.')
  expect(weekly).toContain('Did any of these include both business and personal expenses?')
  expect(weekly).toContain('businessAmountCents')
 })
 it('keeps sweep instructions and actions visible before a long list',()=>{
  expect(weekly).toContain('weekly-sweep-intro')
  expect(weekly).toContain('weekly-sweep-actions')
  expect(weekly).toContain('Mark as personal')
  expect(weekly).toContain('{selectedCount} selected')
  expect(weekly).toContain("stage==='personal'?'personal':'business + personal'")
  expect(weekly).toContain('None were {noun}')
  expect(weekly).toContain('Continue with selected')
  expect(weekly).toContain('How much of the')
  expect(styles).toContain('body { overflow-x: clip; overflow-y: visible; }')
  expect(styles).toContain('.weekly-sweep-actions { position: sticky;')
 })
 it('uses stage-specific accessible checkbox names and keeps final review clean',()=>{
  expect(weekly).toContain('Mark ${item.merchant} as personal')
  expect(weekly).toContain('Mark ${item.merchant} as business and personal')
  expect(weekly).toContain("if(!review.snapshotId)return <WorkflowReview")
  expect(weekly).not.toMatch(/function FinalReview[\s\S]*?<input type="checkbox"/)
 })
 it('shows readable transaction facts and receipt state',()=>{
  expect(weekly).toContain('weekly-transaction-meta')
  expect(weekly).toContain("item.hasReceipt?'Receipt attached':'No receipt'")
  expect(weekly).toContain('ReceiptUploadAction')
 })
 it('keeps questions period-scoped and final presentation gated',()=>{
  expect(questions).toContain('question.transaction.date>=query.start!')
  expect(processing).toContain("stage==='final'")
  expect(processing).toContain('if(!workflowReady||questions>0)')
  expect(processing).toContain('supersededWorkflowEvents')
  expect(processing).toContain('periodRecordIds(loaded.records')
  expect(weeklyReadModel).toContain('supersededWorkflowEvents')
 })
 it('includes mileage before final review',()=>{
  expect(weekly).toContain('Did you drive for your business this week?')
  expect(weekly).toContain('Add another trip')
 })
 it('advances documentation only through a persisted include/exclude decision',()=>{
  expect(weekly).toContain("advance('include_missing')")
  expect(weekly).toContain("advance('exclude_missing')")
  expect(weekly).toContain("decideOne(item,'include_missing')")
  expect(weekly).toContain("decideOne(item,'exclude_missing')")
  expect(weekly).toContain('setEventId(result.eventId??eventId)')
  expect(weekly).toContain('completeStage:false')
  expect(weekly).toContain("stage==='documentation'&&missing.length>0")
  expect(weekly).toContain("['business','mixed_use'].includes(item.treatment)")
 })
 it('opens canonical missing-documentation requests before entering that stage',()=>{
  expect(workflowRoute).toContain('ensurePeriodDocumentationRequests')
  expect(workflowRoute).toContain("open_bookkeeping_documentation_request")
  expect(workflowRoute).toContain("p_reason:'MISSING_SUPPORTING_DOCUMENTATION'")
 })
 it('makes workflow pause controls functional without claiming confirmation',()=>{
  expect(weekly).toContain('onClick={()=>setPaused(true)}>Not right now</button>')
  expect(weekly).toContain('Nothing has been confirmed. You can continue when you’re ready.')
  expect(weekly).toContain('onClick={()=>setPaused(false)}>Continue this review</button>')
 })
 it('renders confirmed and deferred final outcomes as different customer states',()=>{
  expect(weekly).toContain("outcome==='confirmed'")
  expect(weekly).toContain('Your weekly review is confirmed.')
  expect(weekly).toContain("outcome==='deferred'")
  expect(weekly).toContain('Nothing was confirmed. Come back whenever you’re ready.')
  expect(weekly).not.toContain('Thanks — I’ve recorded your review.')
  expect(periodActionRoute).toContain("state:body.action")
 })
 it('binds both customer outcomes to the exact presented snapshot',()=>{
  expect(periodActionRoute).toContain("['presented','correction_linked'].includes(current.data.event_type)")
  expect(periodActionRoute).toContain('current.data.review_snapshot_id!==body.snapshotId')
  expect(periodActionRoute).toContain("p_event_type:body.action")
 })
 it('does not reopen a deferred review as an unfinished workflow on refresh',()=>{
  expect(weeklyReadModel).toContain("if(leaf?.event_type==='deferred')return null")
  expect(weeklyReadModel).toContain("['confirmed','closed_unreviewed'].includes(leaf.event_type)")
 })
})
