-- Baseline the schema used by the existing application.
--
-- This migration is intentionally additive so it can initialize a fresh project
-- or be adopted by the existing Supabase project without dropping user data.

create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  key text not null unique,
  label text not null
);

create table if not exists public.rulesets (
  id bigint generated by default as identity primary key,
  vertical text not null,
  name text not null,
  rules jsonb not null default '[]'::jsonb
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  vertical text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  date date,
  vendor text,
  description text,
  amount numeric,
  category_key text references public.categories(key),
  source text,
  pack text,
  imported_at timestamptz,
  meta jsonb,
  receipt_waived boolean,
  receipt_note text,
  status text,
  created_from_receipt_id uuid,
  needs_review boolean,
  amount_cents integer not null default 0,
  posted_at date,
  currency text,
  raw_description text,
  normalized_description text,
  source_account_id text,
  dedupe_hash text,
  created_at timestamptz not null default now(),
  approved boolean not null default false,
  notes text
);

create table if not exists public.receipts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  transaction_id uuid references public.transactions(id) on delete set null,
  storage_path text not null,
  mime_type text not null,
  bytes integer not null,
  ocr_json jsonb,
  vendor_hint text,
  date_hint date,
  total_hint numeric,
  created_at timestamptz not null default now(),
  original_name text,
  ocr_provider text,
  ocr_status text,
  ocr_confidence numeric
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'transactions_created_from_receipt_id_fkey'
      and conrelid = 'public.transactions'::regclass
  ) then
    alter table public.transactions
      add constraint transactions_created_from_receipt_id_fkey
      foreign key (created_from_receipt_id)
      references public.receipts(id)
      on delete set null;
  end if;
end
$$;

create table if not exists public.bank_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  status text not null,
  token_json jsonb not null,
  created_at timestamptz not null default now(),
  last_sync_at timestamptz
);

create table if not exists public.teller_auth_codes (
  user_id uuid primary key references auth.users(id) on delete cascade,
  code text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  stripe_customer_id text not null,
  stripe_subscription_id text not null,
  price_id text not null,
  plan text not null,
  status text not null,
  current_period_end timestamptz,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.waitlist (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  source text,
  created_at timestamptz not null default now(),
  user_agent text,
  ip_address text,
  name text
);

create table if not exists public.waitlist_submissions (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  token uuid not null,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  ip_hash text,
  user_agent text,
  referer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  status text not null
);

-- This legacy table has no owner column. Its API remains disabled until a later
-- migration can attach rows to a business without guessing ownership.
create table if not exists public.mileage_trips (
  id uuid primary key default gen_random_uuid(),
  date date not null,
  purpose text not null,
  start_label text not null,
  end_label text not null,
  miles numeric not null,
  client text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists transactions_user_posted_at_idx
  on public.transactions (user_id, posted_at desc);
create index if not exists transactions_user_date_idx
  on public.transactions (user_id, date desc);
create index if not exists transactions_user_status_idx
  on public.transactions (user_id, status);
create index if not exists transactions_user_category_idx
  on public.transactions (user_id, category_key);
create index if not exists receipts_user_created_at_idx
  on public.receipts (user_id, created_at desc);
create index if not exists receipts_transaction_id_idx
  on public.receipts (transaction_id);
create index if not exists bank_connections_user_id_idx
  on public.bank_connections (user_id);
create unique index if not exists subscriptions_stripe_customer_id_idx
  on public.subscriptions (stripe_customer_id);
create unique index if not exists subscriptions_stripe_subscription_id_idx
  on public.subscriptions (stripe_subscription_id);
create unique index if not exists waitlist_email_lower_idx
  on public.waitlist (lower(email));
create unique index if not exists waitlist_submissions_token_idx
  on public.waitlist_submissions (token);

alter table public.profiles enable row level security;
alter table public.transactions enable row level security;
alter table public.receipts enable row level security;
alter table public.bank_connections enable row level security;
alter table public.teller_auth_codes enable row level security;
alter table public.subscriptions enable row level security;
alter table public.waitlist enable row level security;
alter table public.waitlist_submissions enable row level security;
alter table public.mileage_trips enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "transactions_select_own" on public.transactions;
create policy "transactions_select_own"
  on public.transactions for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "transactions_insert_own" on public.transactions;
create policy "transactions_insert_own"
  on public.transactions for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "transactions_update_own" on public.transactions;
create policy "transactions_update_own"
  on public.transactions for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "transactions_delete_own" on public.transactions;
create policy "transactions_delete_own"
  on public.transactions for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "receipts_select_own" on public.receipts;
create policy "receipts_select_own"
  on public.receipts for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "receipts_insert_own" on public.receipts;
create policy "receipts_insert_own"
  on public.receipts for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "receipts_update_own" on public.receipts;
create policy "receipts_update_own"
  on public.receipts for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "receipts_delete_own" on public.receipts;
create policy "receipts_delete_own"
  on public.receipts for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "bank_connections_select_own" on public.bank_connections;
create policy "bank_connections_select_own"
  on public.bank_connections for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "teller_auth_codes_own" on public.teller_auth_codes;
create policy "teller_auth_codes_own"
  on public.teller_auth_codes for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- Reference data is readable by signed-in users and is written only by the
-- service role or migrations.
alter table public.categories enable row level security;
alter table public.rulesets enable row level security;

drop policy if exists "categories_read_authenticated" on public.categories;
create policy "categories_read_authenticated"
  on public.categories for select
  to authenticated
  using (true);

drop policy if exists "rulesets_read_authenticated" on public.rulesets;
create policy "rulesets_read_authenticated"
  on public.rulesets for select
  to authenticated
  using (true);

comment on table public.transactions is
  'Legacy mutable transaction model retained for UI compatibility during Milestone 1.';
comment on table public.bank_connections is
  'Legacy provider connection storage. Teller is deprecated; no new Teller connections are allowed.';
comment on table public.mileage_trips is
  'Legacy unowned mileage data. API access is disabled until ownership is migrated safely.';
