-- Durable external delivery of minimized critical operational alerts.
create table public.operational_alert_delivery_outbox(
 id uuid primary key default gen_random_uuid(),alert_id uuid not null references public.lifecycle_operational_alerts(id) on delete restrict,
 semantic_key text not null unique,incident_window timestamptz not null,recipient_ciphertext text not null,
 recipient_hash text not null check(recipient_hash~'^[a-f0-9]{64}$'),scheduled_for timestamptz not null,
 status text not null default'pending'check(status in('pending','processing','retryable','delivered','terminal_failed')),
 attempt_count integer not null default 0 check(attempt_count>=0),lease_token uuid,lease_expires_at timestamptz,next_attempt_at timestamptz,
 provider_message_id text,provider_message_fingerprint text,provider_delivery_status text not null default'accepted'check(provider_delivery_status in('accepted','delivered','delayed','bounced','complained','failed','suppressed')),
 provider_delivery_updated_at timestamptz,safe_failure_code text check(safe_failure_code is null or safe_failure_code~'^[A-Z0-9_]{1,100}$'),delivered_at timestamptz,
 recipient_expires_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(alert_id,incident_window));
create index operational_alert_delivery_due_idx on public.operational_alert_delivery_outbox(status,scheduled_for,next_attempt_at,lease_expires_at);
alter table public.operational_alert_delivery_outbox enable row level security;revoke all on public.operational_alert_delivery_outbox from public,anon,authenticated;grant all on public.operational_alert_delivery_outbox to service_role;
alter table public.lifecycle_notification_provider_events add column operational_delivery_id uuid references public.operational_alert_delivery_outbox(id) on delete restrict;
alter table public.lifecycle_notification_provider_events add constraint lifecycle_provider_event_one_target check(num_nonnulls(notification_id,operational_delivery_id)<=1);

create or replace function public.claim_due_operational_alert_deliveries(p_limit integer,p_lease_token uuid,p_now timestamptz default now())returns setof public.operational_alert_delivery_outbox language plpgsql security definer set search_path=''as $$begin return query with selected as(select id from public.operational_alert_delivery_outbox where scheduled_for<=p_now and recipient_expires_at>p_now and(status='pending'or(status='retryable'and coalesce(next_attempt_at,p_now)<=p_now)or(status='processing'and lease_expires_at<=p_now))order by scheduled_for for update skip locked limit least(greatest(p_limit,1),25)),claimed as(update public.operational_alert_delivery_outbox d set status='processing',lease_token=p_lease_token,lease_expires_at=p_now+interval'2 minutes',attempt_count=attempt_count+1,updated_at=p_now from selected where d.id=selected.id returning d.*)select * from claimed;end$$;
create or replace function public.complete_operational_alert_delivery(p_id uuid,p_lease_token uuid,p_provider_id text,p_provider_fingerprint text,p_now timestamptz default now())returns boolean language plpgsql security definer set search_path=''as $$declare changed integer;begin update public.operational_alert_delivery_outbox set status='delivered',provider_message_id=left(p_provider_id,200),provider_message_fingerprint=left(p_provider_fingerprint,128),delivered_at=p_now,recipient_ciphertext='',recipient_expires_at=p_now,lease_token=null,lease_expires_at=null,next_attempt_at=null,safe_failure_code=null,updated_at=p_now where id=p_id and status='processing'and lease_token=p_lease_token;get diagnostics changed=row_count;return changed=1;end$$;
create or replace function public.fail_operational_alert_delivery(p_id uuid,p_lease_token uuid,p_safe_code text,p_permanent boolean,p_now timestamptz default now())returns boolean language plpgsql security definer set search_path=''as $$declare changed integer;attempt integer;terminal boolean;begin select attempt_count into attempt from public.operational_alert_delivery_outbox where id=p_id and status='processing'and lease_token=p_lease_token for update;if not found then return false;end if;terminal:=p_permanent or attempt>=6;update public.operational_alert_delivery_outbox set status=case when terminal then'terminal_failed'else'retryable'end,safe_failure_code=case when p_safe_code~'^[A-Z0-9_]{1,100}$'then p_safe_code else'OPERATIONAL_ALERT_DELIVERY_FAILED'end,next_attempt_at=case when terminal then null else p_now+(least(60,power(2,attempt)::integer)*interval'1 minute')end,lease_token=null,lease_expires_at=null,updated_at=p_now,recipient_expires_at=case when terminal then least(recipient_expires_at,p_now+interval'30 days')else recipient_expires_at end where id=p_id and status='processing'and lease_token=p_lease_token;get diagnostics changed=row_count;return changed=1;end$$;
revoke execute on function public.claim_due_operational_alert_deliveries(integer,uuid,timestamptz),public.complete_operational_alert_delivery(uuid,uuid,text,text,timestamptz),public.fail_operational_alert_delivery(uuid,uuid,text,boolean,timestamptz)from public,anon,authenticated;
grant execute on function public.claim_due_operational_alert_deliveries(integer,uuid,timestamptz),public.complete_operational_alert_delivery(uuid,uuid,text,text,timestamptz),public.fail_operational_alert_delivery(uuid,uuid,text,boolean,timestamptz)to service_role;

create or replace function public.record_resend_lifecycle_webhook(p_event_key_hash text,p_event_type text,p_provider_message_id text,p_provider_message_fingerprint text,p_occurred_at timestamptz)returns boolean language plpgsql security definer set search_path=''as $$
declare lifecycle public.lifecycle_notification_outbox%rowtype;operational public.operational_alert_delivery_outbox%rowtype;inserted_id uuid;next_status text;safe_code text;
begin if p_event_key_hash!~'^[a-f0-9]{64}$'or p_provider_message_fingerprint!~'^[a-f0-9]{64}$'or p_event_type not in('email.delivered','email.delivery_delayed','email.bounced','email.complained','email.failed','email.suppressed')then raise exception'invalid provider event';end if;
 select*into lifecycle from public.lifecycle_notification_outbox where provider_message_id=p_provider_message_id limit 1;if lifecycle.id is null then select*into operational from public.operational_alert_delivery_outbox where provider_message_id=p_provider_message_id limit 1;end if;
 insert into public.lifecycle_notification_provider_events(event_key_hash,notification_id,operational_delivery_id,event_type,provider_message_fingerprint,occurred_at)values(p_event_key_hash,lifecycle.id,operational.id,p_event_type,p_provider_message_fingerprint,p_occurred_at)on conflict(event_key_hash)do nothing returning id into inserted_id;if inserted_id is null then return false;end if;
 next_status=case p_event_type when'email.delivered'then'delivered'when'email.delivery_delayed'then'delayed'when'email.bounced'then'bounced'when'email.complained'then'complained'when'email.failed'then'failed'else'suppressed'end;
 if lifecycle.id is not null then if lifecycle.provider_delivery_status not in('bounced','complained','failed','suppressed')or next_status in('bounced','complained','failed','suppressed')then update public.lifecycle_notification_outbox set provider_delivery_status=next_status,provider_delivery_updated_at=p_occurred_at,updated_at=now()where id=lifecycle.id;end if;if next_status in('bounced','complained','failed','suppressed')then safe_code=case next_status when'bounced'then'RESEND_EMAIL_BOUNCED'when'complained'then'RESEND_EMAIL_COMPLAINED'when'failed'then'RESEND_EMAIL_FAILED'else'RESEND_EMAIL_SUPPRESSED'end;insert into public.lifecycle_operational_alerts(alert_key,alert_type,severity,subject_hash,safe_code,last_seen_at)values('provider-delivery:'||lifecycle.id,'notification_provider_failure','critical',lifecycle.recipient_hash,safe_code,now())on conflict(alert_key)do update set safe_code=excluded.safe_code,last_seen_at=excluded.last_seen_at,occurrence_count=public.lifecycle_operational_alerts.occurrence_count+1,status='open';end if;
 elsif operational.id is not null then if operational.provider_delivery_status not in('bounced','complained','failed','suppressed')or next_status in('bounced','complained','failed','suppressed')then update public.operational_alert_delivery_outbox set provider_delivery_status=next_status,provider_delivery_updated_at=p_occurred_at,status=case when next_status in('bounced','complained','failed','suppressed')then'terminal_failed'else status end,safe_failure_code=case when next_status in('bounced','complained','failed','suppressed')then upper('RESEND_ALERT_'||next_status)else safe_failure_code end,updated_at=now()where id=operational.id;end if;end if;return true;end$$;
