import {NextResponse}from'next/server'
import{createServerSupabase}from'../../../../utils/supabase/server'
import{createServerAdminSupabase}from'../../../../utils/supabase/admin'
import{createStripeClient,stripePlanMetadata}from'../../../lib/membership/stripe'
import{stripePriceForPlan}from'../../../lib/membership/plans'
type Action='upgrade'|'downgrade'|'cancel_downgrade'|'cancel'|'resume'
export async function POST(request:Request){try{const supabase=await createServerSupabase(),{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Sign in to update membership.'},{status:401})
 const business=await supabase.from('businesses').select('id').eq('owner_user_id',user.id).single();if(!business.data)return NextResponse.json({error:'Membership unavailable.'},{status:404})
 const body=await request.json().catch(()=>null)as{action?:Action;requestKey?:string}|null
 if(!body||!['upgrade','downgrade','cancel_downgrade','cancel','resume'].includes(String(body.action))||typeof body.requestKey!=='string'||body.requestKey.length<8||body.requestKey.length>200)return NextResponse.json({error:'Choose a valid membership change.'},{status:400})
 const admin=createServerAdminSupabase(),[membership,link]=await Promise.all([admin.from('business_memberships').select('*').eq('business_id',business.data.id).single(),admin.from('membership_provider_links').select('*').eq('business_id',business.data.id).single()])
 if(!membership.data||!link.data?.provider_subscription_id)return NextResponse.json({error:'A Stripe membership is required for this change.'},{status:409})
 const stripe=createStripeClient(),subscription=await stripe.subscriptions.retrieve(link.data.provider_subscription_id),item=subscription.items.data[0];if(!item)return NextResponse.json({error:'Membership update is still processing.'},{status:409})
 let eventType:string,lifecycle='active',scheduledPlan:string|null=null,scheduledAt:string|null=null,cancelAtPeriodEnd=false
 if(body.action==='upgrade'){if(membership.data.plan!=='expenses')return NextResponse.json({error:'Business is already active.'},{status:409});await stripe.subscriptions.update(subscription.id,{items:[{id:item.id,price:stripePriceForPlan('business')}],proration_behavior:'always_invoice',payment_behavior:'pending_if_incomplete',metadata:stripePlanMetadata(business.data.id,'business')},{idempotencyKey:`membership-upgrade-${business.data.id}-${body.requestKey}`});return NextResponse.json({ok:true,message:'Your Business upgrade is being confirmed.'})}
 if(body.action==='cancel_downgrade'){if(!membership.data.scheduled_plan)return NextResponse.json({error:'No membership change is scheduled.'},{status:409});const scheduleId=typeof subscription.schedule==='string'?subscription.schedule:subscription.schedule?.id;if(!scheduleId)return NextResponse.json({error:'The scheduled change is still processing.'},{status:409});await stripe.subscriptionSchedules.release(scheduleId);eventType='downgrade_canceled'}
 else if(body.action==='downgrade'){if(membership.data.plan!=='business')return NextResponse.json({error:'Expenses is already active.'},{status:409});if(membership.data.scheduled_plan)return NextResponse.json({ok:true,message:'Your switch to Expenses is already scheduled.'});const end=item.current_period_end,schedule=await stripe.subscriptionSchedules.create({from_subscription:subscription.id},{idempotencyKey:`membership-downgrade-${business.data.id}-${body.requestKey}`});await stripe.subscriptionSchedules.update(schedule.id,{end_behavior:'release',phases:[{start_date:item.current_period_start,end_date:end,items:[{price:item.price.id,quantity:item.quantity??1}]},{start_date:end,items:[{price:stripePriceForPlan('expenses'),quantity:1}],metadata:stripePlanMetadata(business.data.id,'expenses')}]});eventType='downgrade_scheduled';scheduledPlan='expenses';scheduledAt=new Date(end*1000).toISOString()}
 else if(body.action==='cancel'){await stripe.subscriptions.update(subscription.id,{cancel_at_period_end:true},{idempotencyKey:`membership-cancel-${business.data.id}-${body.requestKey}`});eventType='cancellation_requested';lifecycle='canceling';cancelAtPeriodEnd=true}
 else{await stripe.subscriptions.update(subscription.id,{cancel_at_period_end:false},{idempotencyKey:`membership-resume-${business.data.id}-${body.requestKey}`});eventType='cancellation_reversed'}
 const recorded=await admin.rpc('record_confirmed_membership_intent',{p_business_id:business.data.id,p_actor_user_id:user.id,p_request_key:body.requestKey,p_event_type:eventType,p_lifecycle:lifecycle,p_scheduled_plan:scheduledPlan,p_scheduled_effective_at:scheduledAt,p_cancel_at_period_end:cancelAtPeriodEnd});if(recorded.error)throw new Error('MEMBERSHIP_INTENT_FAILED');return NextResponse.json({ok:true})
}catch{return NextResponse.json({error:'We could not update your membership. Please try again.'},{status:503})}}
